---
title: "Demographic statistics PD"
author: "Alba"
date: "`r Sys.Date()`"
output:
   #BiocStyle::html_document:
   html_document:
     
     code_folding: hide
editor_options:
  chunk_output_type: console
params:
  FIGPATH: "figures/"
  d.out: "./"
---

# Preparations
## Set global options

```{r style, results="asis", cache=FALSE, message = F}
# Set knit global options
library("knitr")
options(digits = 2, width = 80)
golden_ratio <- (1 + sqrt(5)) / 2
opts_chunk$set(echo = TRUE,
               tidy = FALSE,
               include = TRUE,
               fig.path = params$FIGPATH,
               dev=c("png",'pdf'),
               fig.height = 5,
               fig.width = 4 * golden_ratio,
               comment = '  ',
               dpi = 300,
               cache = FALSE)


# Pretty outputs
library("rmarkdown")
#library("BiocStyle")
library("ggthemes") # add ggplot2 themes
library("ggplot2")
library("ggpubr")

# Set seed for reproducibility
set.seed(100)

# Set plotting theme
theme_set(theme_few(base_size = 14))

# Set output directory
d.out <- params$d.out
rm(params)
```


## Load libraries for the session
```{r libraries, message=FALSE}
library("magrittr")
library("ggplot2")
library("tidyverse")
library("readxl")
library("dada2")
library("phyloseq")
library("gridExtra")
library("vegan")
library("plyr")
library("scales")
library("reshape2")
library("DESeq2")
library("dplyr") #for data manipulation
library("msa") #multiple sequence alignment
library("ape") #to create phylogenetic tree
library("randomForest") 
library("caret") 
library("broom")
library("mlbench")
library("plotROC")
library("compareGroups")
library("tidyr")
library("knitr")

```

## Import data

Number of participants in each Group


```{r}
#import MS table
library(readxl)
Datensatz <- read_excel("~/Documents/Daten /Datensatz.xlsx")
View(Datensatz)


pd1 <- as.data.frame(Datensatz)

```

subset metadata table

```{r}

a <- data.frame(colnames(pd1))

dt <- pd1[, c("ID", "Rauchen?", "BMI", "Alter", "Geschlecht")]

###dt <- pd1[rows, column]

```

edit table

```{r}
#remove missing values

dt1 <- dt[!(dt$Alter %in% c("empty choice", "empty integer")), ]
dt2 <- dt1[!(dt1$BMI %in% c("empty choice", "empty integer")), ]

```

edit age

```{r}

dt2$Alter <- floor(as.numeric(dt2$Alter))

```

save as excel table 

```{r}
install.packages("writexl")
library(writexl)
write_xlsx(dt2, path = "BMI.xlsx")

```

mean age
```{r}

mean.age <- mean(dt2$Alter)
sd.age <- sd(dt2$Alter)

```

the same for BMI: mean and sd

```{r}
dt2$BMI <- as.numeric(as.character(dt2$BMI))
mean.BMI <- mean(dt2$BMI)
sd.BMI <- sd(dt2$BMI)

```

number of smokers
```{r}
c <- dt2[(dt2$Rauchen. %in% "Ja"), ] #Raucher = 43

# Nicht Raucher = 472-43
```
number of male and female

```{r}
b <- dt2[(dt2$Geschlecht %in% "w"), ] #females = 174

#males = 472-174 
```


```{r}

library(writexl)
write_xlsx(dt2, "metadata.edit.xlsx")

```


```{r}
install.packages("officer")
install.packages("flextable")
```

```{r}

# Laden der Pakete
library(officer)
library(flextable)

# Erstelle eine Tabelle mit den berechneten Werten
results <- data.frame(
  Parameter = c("Mittelwert Alter", "Standardabweichung Alter", 
                "Mittelwert BMI", "Standardabweichung BMI", 
                "Anzahl Raucher", "Anzahl Nichtraucher", 
                "Anzahl Frauen", "Anzahl Männer"),
  Wert = c(mean.age, sd.age, mean.BMI, sd.BMI, 
           nrow(c), nrow(dt2) - nrow(c), 
           nrow(b), nrow(dt2) - nrow(b))
)

# Erstelle eine Flextable aus dem DataFrame
ft <- flextable(results)

# Formatierung der Tabelle (optional)
ft <- autofit(ft)  # Automatische Anpassung der Spaltenbreite

# Erstelle ein neues Word-Dokument
doc <- read_docx()

# Füge die Flextable dem Dokument hinzu
doc <- body_add_flextable(doc, value = ft)

# Speichere das Word-Dokument
print(doc, target = "Ergebnisse_Tabelle.docx")

```

#session info ()