---
title: "MaAsLin"
author: "Mona Hildebrandt "
date: "`r Sys.Date()`"  
output:
   #BiocStyle::html_document:
   html_document:
     code_folding: hide
editor_options:
  chunk_output_type: console
params:
  FIGPATH: "figures/"
  d.out: "./"
---

#library

```{r}
library("pasilla")
library("tidyverse")
library("DESeq2")
library("pheatmap")
library("RColorBrewer")
library("apeglm")

library("DEGreport")
#Note: In some versions of Mac DEGreport will not be loaded successfully,
#Try install Xquarz, restart Mac and R studio, and try to load again
# https://www.xquartz.org/
```

#import data 
```{r}
# Phyloseq object AD filtered samples
d.ps.filter.ad.st <- "~/Documents/dietproject"
ps.filter.ad.st <- "/3.ps.filter.pd.abundance.rds" %>%
  paste0(d.ps.filter.ad.st,"/", .) %>% 
  readRDS() 
ps.filter.ad.st


```

subset only stool samples:
```{r}
ps.st <- subset_samples(ps.filter.ad.st, !(sample_names(ps.filter.ad.st) %in% "23Jul94-DL185"))
ps.st
str(ps.st)
```


```{r}
# split/convert in phyloseq one table  
dt <- psmelt(ps.st)
```

#prepare data
```{r}
dt2 <- as.data.frame(dt)
```

```{r}
feature_table <- dt2 %>%
  dplyr::select(Sample, Genus, Abundance) %>%
  dplyr::group_by(Sample, Genus)
  
```

```{r}
feature_table2 <- feature_table %>%  
  dplyr::summarise(Abundance = sum(Abundance, na.rm = TRUE))
```

```{r}
feature_table3 <- feature_table2 %>%  
  pivot_wider(names_from = Sample, values_from = Abundance, values_fill = 0) %>%
  column_to_rownames("Genus")
```



```{r}
# Metadaten erstellen
meta_data <- dt %>%
  dplyr::select(Sample, Rauchen., BMI, Alter, Geschlecht, Protein.in.., Fett.in.., Fett_MUFS.in.., davon_Zucker.in.., 
         Kohlenhydrate.in.., Ballaststoffe.in.., Cholesterin, Natrium, Kalium, Calcium, Phosphor, Magnesium, Eisen) %>%
  dplyr::distinct() %>%
  tibble::column_to_rownames("Sample")
```



# MaAsLin
#protein
```{r}
fit_data <- Maaslin2(
  input_data = feature_table3,
  input_metadata = meta_data,
  output = "maaslin3_results",
  fixed_effects = c("Protein.in..", "BMI", "Alter", "Geschlecht", "Rauchen."),
  normalization = "TSS",  
  transform = "LOG",
  analysis_method = "LM",
  min_prevalence = 0.1,
  cores = 4
)
```


```{r}
output_dir <- "/home/username/Documents/maaslin3_results"
```


#carbohydrate
```{r}
fit_data <- Maaslin2(
  input_data = feature_table3,
  input_metadata = meta_data,
  output = "maaslin3_results_Carbohydrate",
  fixed_effects = c("Kohlenhydrate.in..", "BMI", "Alter", "Geschlecht", "Rauchen."),
  normalization = "TSS",  
  transform = "LOG",
  analysis_method = "LM",
  min_prevalence = 0.1,
  cores = 4
)
```

```{r}
output_dir <- "/home/username/Documents/maaslin3_results_Carbohydrate"
```


#fat 
```{r}
fit_data <- Maaslin2(
  input_data = feature_table3,
  input_metadata = meta_data,
  output = "maaslin3_results_fat",
  fixed_effects = c("Fett.in..", "BMI", "Alter", "Geschlecht", "Rauchen."),
  normalization = "TSS",  
  transform = "LOG",
  analysis_method = "LM",
  min_prevalence = 0.1,
  cores = 4
)
```

```{r}
output_dir <- "/home/username/Documents/maaslin3_results_fat"
```


#fat_PUFA
```{r}
fit_data <- Maaslin2(
  input_data = feature_table3,
  input_metadata = meta_data,
  output = "maaslin3_results_fat_PUFA",
  fixed_effects = c("Fett_MUFS.in..", "BMI", "Alter", "Geschlecht", "Rauchen."),
  normalization = "TSS",  
  transform = "LOG",
  analysis_method = "LM",
  min_prevalence = 0.1,
  cores = 4
)
```

```{r}
output_dir <- "/home/username/Documents/maaslin3_results_fat_PUFA"
```


#sugar
```{r}
fit_data <- Maaslin2(
  input_data = feature_table3,
  input_metadata = meta_data,
  output = "maaslin3_results_sugar",
  fixed_effects = c("davon_Zucker.in..", "BMI", "Alter", "Geschlecht", "Rauchen."),
  normalization = "TSS",  
  transform = "LOG",
  analysis_method = "LM",
  min_prevalence = 0.1,
  cores = 4
)
```

```{r}
output_dir <- "/home/username/Documents/maaslin3_results_sugar"
```

#fiber 
```{r}
fit_data <- Maaslin2(
  input_data = feature_table3,
  input_metadata = meta_data,
  output = "maaslin3_results_fiber",
  fixed_effects = c("Ballaststoffe.in..", "BMI", "Alter", "Geschlecht", "Rauchen."),
  normalization = "TSS",  
  transform = "LOG",
  analysis_method = "LM",
  min_prevalence = 0.1,
  cores = 4
)
```

```{r}
output_dir <- "/home/username/Documents/maaslin3_results_fiber"
```

#Cholesterol
```{r}
fit_data <- Maaslin2(
  input_data = feature_table3,
  input_metadata = meta_data,
  output = "maaslin3_results_cholesterol",
  fixed_effects = c("Cholesterin", "BMI", "Alter", "Geschlecht", "Rauchen."),
  normalization = "TSS",  
  transform = "LOG",
  analysis_method = "LM",
  min_prevalence = 0.1,
  cores = 4
)
```

```{r}
output_dir <- "/home/username/Documents/maaslin3_results_cholesterol"
```

#sodium
```{r}
fit_data <- Maaslin2(
  input_data = feature_table3,
  input_metadata = meta_data,
  output = "maaslin3_results_sodium",
  fixed_effects = c("Natrium", "BMI", "Alter", "Geschlecht", "Rauchen."),
  normalization = "TSS",  
  transform = "LOG",
  analysis_method = "LM",
  min_prevalence = 0.1,
  cores = 4
)
```

```{r}
output_dir <- "/home/username/Documents/maaslin3_results_sodium"
```

#potassium
```{r}
fit_data <- Maaslin2(
  input_data = feature_table3,
  input_metadata = meta_data,
  output = "maaslin3_results_potassium",
  fixed_effects = c("Kalium", "BMI", "Alter", "Geschlecht", "Rauchen."),
  normalization = "TSS",  
  transform = "LOG",
  analysis_method = "LM",
  min_prevalence = 0.1,
  cores = 4
)
```

```{r}
output_dir <- "/home/username/Documents/maaslin3_results_potassium"
```

#Calcium
```{r}
fit_data <- Maaslin2(
  input_data = feature_table3,
  input_metadata = meta_data,
  output = "maaslin3_results_Calcium",
  fixed_effects = c("Calcium", "BMI", "Alter", "Geschlecht", "Rauchen."),
  normalization = "TSS",  
  transform = "LOG",
  analysis_method = "LM",
  min_prevalence = 0.1,
  cores = 4
)
```

```{r}
output_dir <- "/home/username/Documents/maaslin3_results_Calcium"
```

#Phosphor
```{r}
fit_data <- Maaslin2(
  input_data = feature_table3,
  input_metadata = meta_data,
  output = "maaslin3_results_Phosphor",
  fixed_effects = c("Phosphor", "BMI", "Alter", "Geschlecht", "Rauchen."),
  normalization = "TSS",  
  transform = "LOG",
  analysis_method = "LM",
  min_prevalence = 0.1,
  cores = 4
)
```

```{r}
output_dir <- "/home/username/Documents/maaslin3_results_Phosphor"
```


#Magnesium
```{r}
fit_data <- Maaslin2(
  input_data = feature_table3,
  input_metadata = meta_data,
  output = "maaslin3_results_Magnesium",
  fixed_effects = c("Magnesium", "BMI", "Alter", "Geschlecht", "Rauchen."),
  normalization = "TSS",  
  transform = "LOG",
  analysis_method = "LM",
  min_prevalence = 0.1,
  cores = 4
)
```

```{r}
output_dir <- "/home/username/Documents/maaslin3_results_Magnesium"
```


#Iron
```{r}
fit_data <- Maaslin2(
  input_data = feature_table3,
  input_metadata = meta_data,
  output = "maaslin3_results_iron",
  fixed_effects = c("Eisen", "BMI", "Alter", "Geschlecht", "Rauchen."),
  normalization = "TSS",  
  transform = "LOG",
  analysis_method = "LM",
  min_prevalence = 0.1,
  cores = 4
)
```

```{r}
output_dir <- "/home/username/Documents/maaslin3_results_iron"
```

```{r}
fit_data <- Maaslin2(
  input_data = feature_table,
  input_metadata = meta_data,
  output = "maaslin3_results_all_nutrients",
  fixed_effects = c("Protein.in..", "Fett.in..", "Fett_MUFS.in..", "davon_Zucker.in..", 
         "Kohlenhydrate.in..", "Ballaststoffe.in..", "Cholesterin", "Natrium", "Kalium", "Calcium", "Phosphor", "Magnesium", "Eisen", "BMI", "Alter", "Geschlecht", "Rauchen."),
  normalization = "TSS",  
  transform = "LOG",
  analysis_method = "LM",
  min_prevalence = 0.1,
  cores = 4
)
```

```{r}

```




#session info 